name: Daily News Bot

on:
  schedule:
    - cron: "0 3 * * *" # Run every day at 9:00 AM UTC
  workflow_dispatch:

jobs:
  fetch_and_send_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Use Python 3.9+

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -r requirements.txt

      - name: Run Python script
        run: python main.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          TARGET_CHAT_ID: ${{ secrets.TARGET_CHAT_ID }}
